config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'projects/manage', to: 'projects#manage', as: 'manage_projects'
  get 'bugs/manage', to: 'bugs#manage', as: 'manage_bugs' 
  # for devise user controller overwrite
  devise_for :users, controllers: { sessions: 'users/sessions'}

  # get all routes prebuilt for your custom model
  resources :users, only: [:index, :show]
  resources :projects, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :bugs, only: [:show, :index, :new, :create, :edit, :update, :destroy]

end

app/models/bug.rb
class Bug < ApplicationRecord
  belongs_to :project
  belongs_to :user
  has_one_attached :image

  enum bug_type: [:feature, :bug]
  enum feature_status: [:feature_new, :feature_started, :feature_completed]
  enum bug_status: [:bug_new, :bug_started, :bug_resolved]
   
  validates :title, presence: true, uniqueness: { scope: :project_id }, length: {minimum: 6, maximum: 100}
  validates :bug_type, presence: true
  validates :feature_status, :bug_status, presence: true
  validates :description, presence: true, length: {minimum: 10, maximum: 500}
  validate :correct_image_type
  validate :deadline_cannot_be_in_the_past
  

  private

  def deadline_cannot_be_in_the_past
    if Date.parse(deadline.to_s).past? || deadline.strftime("%I:%M%p") < Time.now.strftime("%I:%M%p")
      errors.add(:deadline, "can't be in the past")
    end
  end

  def correct_image_type
    if image.attached? && !image.content_type.in?(%w(image/png image/gif))
      errors.add(:image, 'Must be a png or a gif file')
    end
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
    #load_and_authorize_resource
    before_action :find_bug, only: [:show, :edit, :update, :destroy]

    def show  
    end

    def index
        if current_user.developer?
            dev_project = Project.where(dev_id: current_user.id)
            @bugs = Bug.where(project_id: dev_project.ids)    
        else
            @bugs = Bug.where(user_id: current_user.id)
        end        
    end

    def manage
        @bugs = Bug.all
    end

    def new
        @projects = Project.all
        @bug = Bug.new
        authorize! :create, @bug
    end

    def create
        @user = current_user
        @bug = @user.bugs.build(bug_params)
        #@bug = Bug.new(params.require(:bug).permit(:title, :description, :bug_type, :feature_status, :bug_status, :deadline, :project_id, :image))
        if @bug.save
            flash[:notice] = "Bug was created successfully"
            redirect_to bug_path(@bug.id)
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        authorize! :update, @bug
    end

    def update
        if @bug.update(bug_params)
            flash[:notice] = "Bug was updated successfully"
            redirect_to bug_path(@bug.id)
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @bug.destroy
        flash[:notice] = "Bug was deleted successfully"
        authorize! :destroy, @bug
        redirect_to manage_bugs_path
    end

    def find_bug
        @bug = Bug.find(params[:id])
    end

    def bug_params
        params.require(:bug).permit(:title, :description, :bug_type, :feature_status, :bug_status, :deadline, :project_id, :image)
    end
    
end

app/views/bugs/_form.html.erb
<div class="row justify-content-center">
    <div class="col-6 text-center">
        <%= form_with(model: @bug, local: true)  do |f| %>
            <p>
                <%= f.label :bug_title %><br/>
                <%= f.text_field :title, class:"form-control" %>
            </p>

            <p>
                <%= f.label :description%><br/>
                <%= f.text_area :description, rows:5, cols:30, class:"form-control"%>
            </p>

            <div class="my-2">
                <%= f.label :bug_type %><br />
                <%= f.label :bug_type, "Feature", :value => "feature"  %>
                <%= f.radio_button :bug_type, "feature", onclick:" checkButton()", class:"form-check-input", id:"feature"%>
                <%= f.label :bug_type, "Bug", :value => "bug"%>
                <%= f.radio_button :bug_type, "bug", onclick:" checkButton()", class:"form-check-input", id:"bug" %>
            </div>

            <div class="div">
                <p class="alert_bug_type_selection" id="para"></p>
            </div>

            <div id="panel1">
                <p>
                    <%= f.label :feature_status%><br/>
                    <%= f.select(:feature_status, Bug.feature_statuses.keys.map {|key| [key.humanize, key]}, {}, {class:"form-select"}) %>
                </p>
            </div>

            <div id="panel2">
                <p>
                    <%= f.label :bug_status%><br/>
                    <%= f.select(:bug_status, Bug.bug_statuses.keys.map {|key| [key.humanize, key]}, {}, {class:"form-select"}) %>
                </p>
            </div>

            <p>
            <%= f.label :select_project%><br/>
            <%= f.select :project_id, Project.where(qa_id: current_user.id).collect {|key| [ key.project_name, key.id ] }, {}, {class:"form-select"}%>
            </p>

            <p>
            <%= f.label :deadline%><br/>
            <%= f.datetime_field :deadline, class:"form-control" %>
            </p>

            <div class="my-3">
                <%= f.label :image, class:"form-label" do %>
                    <% if f.object.image.attached? %>
                        File attached: <i id="role_text"><%= f.object.image.filename %></i>. Choose to replace it.
                    <% else %>
                        No file has been uploaded yet. Please pick a file.
                    <% end %>
                <% end %>
                <%= f.file_field :image, class:"form-control"%>
            </div>

            <p>
                <%= f.submit class:"btn btn-outline-success"%>
            </p>
        <% end %>
        <p><%= link_to 'Cancel', :back, class:"btn btn-outline-primary"%></p>
    </div>
</div>

<script>
    var box1= document.querySelector('#panel1')
    var box2= document.querySelector("#panel2")
    
    function checkButton(){
    if(document.getElementById('feature').checked) { 
        document.getElementById("para").innerHTML = "You have selected type: " + document.getElementById("feature").value + ". Please select below";
        box1.style.display = "block"
        box2.style.display = "none" 
        }
    else { 
        document.getElementById("para").innerHTML = "You have selected type: " + document.getElementById("bug").value + ". Please select below";
        box1.style.display = "none"
        box2.style.display = "block"   
    }
    }
</script>

app/views/bugs/edit.html.erb
<%= render 'shared/bug_errors'%>

<div class="container py-3 my-5 bg_container">
    <div class="row justify-content-center">
        <div class="col-12 text-center">
            <h2><strong>Update Bug</strong></h2>
            <hr class="my-4">
        </div>
    </div>
    <%= render 'form'%> 
</div>

app/views/bugs/index.html.erb
<div class="row py-3 my-5 text-center">
    <h2><strong>All Bugs</strong></h2>
</div>

<div class="row">
  <% if @bugs.exists? %>
      <% @bugs.each do |bug|%>
          <div class="col-sm-6 py-3">
              <div class="card">
                  <div class="card-body">
                      <h5 class="card-title"><%= truncate(bug.title, length: 45)%></h5>
                      <p class="card-text"><%= truncate(bug.description, length: 45)%></p>
                      <%= link_to 'Read more', bug_path(bug), class:"btn btn-outline-primary" %>
                  </div>
              </div>
          </div>
      <% end %>
  <% else%>
    <div class="text-center"><h4>No Bug Exists</h4></div>
  <% end %>
</div>

<p>
    <% if can? :create, Bug %>
        <%= link_to 'Create a new Bug', new_bug_path, class: "btn btn-outline-success" %> |
    <% end %>
    <%= link_to 'Home', root_path, class: "btn btn-outline-primary" %>
</p>

app/views/bugs/manage.html.erb
<div class="container py-3 my-5 bg_container text-center">
    <div class="row">
    <h2><strong>Manage Bugs</strong></h2>
    </div>
    <hr class="my-4">
    <div class="row">     
        <% if @bugs.exists? %>
            <% @bugs.each do |bug|%>
                <div class="col-sm-4 py-3">
                    <div class="card">
                        <div class="card-body">
                            <p>Bug Id: &nbsp;<%= bug.id %></p>
                            <p class="card-title"><%= truncate(bug.title, length: 32)%></p>
                            <p class="card-text"><%= truncate(bug.description, length: 32)%></p>
                            <p>Bug Type: <%= bug.bug_type%></p>
                            <p>Creator: &nbsp;<%= bug.user_id%></p>
                            <p>Belongs to Project: &nbsp;<%= bug.project_id%></p>
                            <p>Feature Status: &nbsp;<%= bug.feature_status%></p>
                            <p>Bug Status: &nbsp;<%= bug.bug_status%></p>
                            <p>Deadline: &nbsp;<%= bug.deadline%></p>
                            <%= link_to 'View', bug_path(bug.id), class: "btn btn-outline-primary" %>
                            <% if can? :update, bug %>
                                <%= link_to 'Edit', edit_bug_path(bug.id), class: "btn btn-outline-primary"%></td>
                            <% end %>
                            <% if can? :destroy, bug %>
                                <%= link_to 'Remove', bug_path(bug.id), method: :delete, data: {confirm: "Are You Sure you want to delete this project?"}, class: "btn btn-outline-danger"%>
                            <% end %>
                        </div>
                    </div>
                </div>
            <% end %>        
        <% else%>
            <div class="text-center"><h4>No Bug Exists</h4></div>
        <% end %>
    </div>
</div>

app/views/bugs/new.html.erb
<%= render 'shared/bug_errors'%>

<div class="container py-3 my-5 bg_container">
    <div class="row justify-content-center">
        <div class="col-12 text-center">
            <h2><strong>Create a New Bug</strong></h2>
            <hr class="my-4">
        </div>
    </div>
    <%= render 'form'%>
</div>

app/views/bugs/show.html.erb
<div class="container py-3 my-5 bg_container">
    <div class="row justify-content-center">
        <div class="col-12 text-center">
            <h2><strong>Bug Detail</strong></h2>
            <hr class="my-4">
        </div>
    </div>        

    <div class="text-center">
        <p>Title: <%= @bug.title%></p>
        <p>Description: <%= @bug.description%></p>
        <p>Bug Type: <%= @bug.bug_type%></p>
        <p>Creator: &nbsp;<%= @bug.user_id%></p>
        <p>Belongs to Project: &nbsp;<%= @bug.project_id%></p>
        <p>Feature Status: <%= @bug.feature_status%></p>
        <p>Bug Status: <%= @bug.bug_status%></p>
        <p>Deadline: <%= @bug.deadline%></p>
    </div>
    <div class="text-center"> 
        <%= image_tag @bug.image, style: "width: 200px; height: 200px" , id:"bug_image" if @bug.image.attached?%>
    </div>
    <div class="py-3">    
        <p class="text-center">
            <% if can? :update, @bug %>
                <%= link_to 'Edit', edit_bug_path(@bug.id), class:"btn btn-outline-success" %>
            <% end %>
            <% if can? :destroy, @bug %>
                <%= link_to 'Delete', bug_path(@bug.id), method: :delete, data: {confirm: "Are You Sure you want to delete this project?"}, class:"btn btn-outline-danger" %>
            <% end %>
            <%= link_to 'All Bugs', bugs_path, class:"btn btn-outline-primary"%>
        </p>
    </div>
</div>