config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'projects/manage', to: 'projects#manage', as: 'manage_projects'
  get 'bugs/manage', to: 'bugs#manage', as: 'manage_bugs' 
  # for devise user controller overwrite
  devise_for :users, controllers: { sessions: 'users/sessions'}

  # get all routes prebuilt for your custom model
  resources :users, only: [:index, :show]
  resources :projects, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :bugs, only: [:show, :index, :new, :create, :edit, :update, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container">
        <span >&copy; Bug Tracking System.</span>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- navigation starts-->
<nav class="navbar navbar-expand-sm navigation">
  <div class="container-fluid">
    <%= link_to 'Bug Tracking System', root_path, class: "nav-link active link_logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user%>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Projects
            </a>
            <ul class="dropdown-menu animate slideIn" aria-labelledby="navbarDropdown">
              <% if can? :create, Project %>
                <li><p class= "text-center"><%= link_to 'Create New Project', new_project_path, class: "dropdown-item" %></li></p>
              <% end %>
              <li><p class= "text-center"><%= link_to 'View Projects', projects_path, class: "dropdown-item" %></li></p>
              <li><p class= "text-center"><%= link_to 'Manage Projects', manage_projects_path, class: "dropdown-item" %></li></p>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Bugs
            </a>
            <ul class="dropdown-menu animate slideIn" aria-labelledby="navbarDropdown">
              <% if can? :create, Bug %>
                <li><p class= "text-center"><%= link_to 'Create New Bug', new_bug_path, class: "dropdown-item" %></li></p>
              <% end %>
              <li><p class= "text-center"><%= link_to 'View Bugs', bugs_path, class: "dropdown-item" %></li></p>
              <li><p class= "text-center"><%= link_to 'Manage Bugs', manage_bugs_path, class: "dropdown-item" %></li></p>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Users
            </a>
            <ul class="dropdown-menu animate slideIn" aria-labelledby="navbarDropdown">
              <li><p class= "text-center"><%= link_to 'View Users', users_path, class: "dropdown-item" %></li></p>
            </ul>
          </li>
        <% end %>
      </ul>
      <% if current_user%>
        <div><strong><i class="px-2 text-muted" ><%= current_user.user_type.capitalize%></i></strong></div>
        <div><%= link_to "Profile", user_path(current_user.id), class: " btn btn-outline-success text-white mx-2"%></div>
        <div><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-warning text-white" %></div>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-success text-white mx-2"%>
        <%= link_to "Log In", new_user_session_path, class: "btn btn-outline-primary text-white"%>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugTrackingSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;1,200&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
 
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>
</html>